### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

Make an vector/array  
in NumPy, a is indeed an object. Specifically, it is an instance of the numpy.ndarray class. This class provides various attributes and methods, such as a.shape and a.size, which allow you to interact with and manipulate the array.

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [7]:
# Get Size
a.itemsize  # int32 is stored in 4 byte

4

In [8]:
# Get total size
a.nbytes  # total 12 bytes for 3 elements

12

In [9]:
# Get number of elements
print(a[1])
print(a.size)  # 3 elements in array a 
print(b.size)

2
3
6


### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c] for a 2D array
# index starting at 0
a[1, 5]

13

In [12]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]  # Note that the "-1" index is excluded
# from the first to the last, step is 2

array([2, 4, 6])

In [15]:
# modifying element(s)
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
# b[0, 1, 1] accesses the element in the first "block" (dimension 0), the second "row" (dimension 1), and the second "column" (dimension 2)
b[0,1,1]

4

In [18]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [19]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [20]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
a.shape

(2, 7)

In [24]:
# Any other number (full_like)
np.full_like(a, 4)  # refering to the shape of array a (2*7)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Random decimal numbers
np.random.rand(4,2)  # generate a random array with size (4, 2) in the range [0, 1)

array([[0.37617495, 0.39017763],
       [0.21995752, 0.34190619],
       [0.8038918 , 0.93569276],
       [0.68826562, 0.47586692]])

In [26]:
np.random.uniform(2,4, size=(3,3))  # generate floats in specified range

array([[3.82282268, 2.80830966, 2.16615425],
       [2.76240821, 2.05706278, 3.00584166],
       [3.99877078, 2.94381662, 3.65686683]])

In [27]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))  # generate random array with element from [-4, 8)

array([[ 3, -4, -3],
       [-4, -4, -2],
       [ 2,  4,  5]])

In [28]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)  # vertically, each as a row
r2 = np.repeat(arr,3, axis=1)  # horizontally, note the repetition pattern
r3 = np.tile(arr, (1, 3)) # The np.tile function repeats the arr array 1 time along the first axis (rows) and 3 times along the second axis (columns).
print(r1)
print(r2)
print(r3)

# np.tile : Purpose: Repeats the whole array along specified axes.
# np.repeat : Purpose: Repeats elements within the array along specified axes.

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]
[[1 2 3 1 2 3 1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z  # modify the elements in array output according to array z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [31]:
a = np.array([1,2,3])
b = a.copy()  # if b=a, then b is just an alias of a, so that a is altered when b is altered
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
a + 2

array([3, 4, 5, 6])

In [34]:
a - 2

array([-1,  0,  1,  2])

In [35]:
a * 2

array([2, 4, 6, 8])

In [36]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [37]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [38]:
a ** 2

array([ 1,  4,  9, 16])

In [39]:
print(a) # the original array is unchanged

[1 2 3 4]


In [40]:
# Take the sin
test = np.cos(a)
print(test)
print(a)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[1 2 3 4]


In [41]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [42]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)  # matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)  # determinant is |A|

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [44]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [45]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)

1

In [47]:
print(np.max(stats, axis=1))  # max elements of each row; axis = 1 operations performs horizontally
print(np.max(stats, axis=0))  # max elements of each column' axis = 0 operations performs vertically

[3 6]
[4 5 6]


In [48]:
print(np.sum(stats, axis=0)) # sum of elements according to rows
print(np.sum(stats, axis=1)) # sum of elements according to columns

[5 7 9]
[ 6 15]


### Reorganizing Arrays

In [49]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))  # the total number should hold after reorganizing
print(after)
print(before)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [50]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # stack vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))  # stack horizontally

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [52]:
filedata = np.genfromtxt('data.txt', delimiter=',')  # generate array from txt file
filedata = filedata.astype('int32')  # change data type
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [53]:
((filedata > 50) & (filedata < 100))  # check the element in range (50, 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [54]:
(~((filedata > 50) & (filedata < 100)))  # not of the above condition "~"

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [55]:
filedata > 50  # examine the condition element-wisekly

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])